### ISSUE TITLE
Peer Review -- ps972

### ISSUE THREAD

**Issue by patcharafyo** [amanjain454/4741-Project#1]
The topic is exciting, and if you can find a good strategy for pricing the subscription, it would improve the pricing process and ensure the company's profit. However, because I did not see your dataset yet, it is quite difficult for me to imagine what is your data look like and evaluate the possibility of your project. There are also a lot of optional data columns that seem quite crucial for the performance of your prediction. The last thing that I want to mention is the definition of a good strategy. I think it may be more apparent if you objectively define your goal. For example, you might set your objective equation or function and build the cost prediction model or strategy base on that.

**Comment by SZ559** [comment]
The project is a mix of the data extrapolation project and algorithm development project. The objective of the project, according to my understanding, is to find the optimal pricing strategy for  commuting service. This is a good field to work on since it could fill the gap of the pricing strategy for commuting service during the peak time. The main dataset used including several attributes from the company’s data. The final price strategy will be made through considering cost of operation, competitor pricing and customer opinions. To achieve that, several machine learning models including cost models will be  

Three points that I like about this proposal:
1.	I think it is a very good topic since it focuses on solving the real world problem and has the potential to fill the gap of the algorithms about pricing strategy of commuting service in India and help the company make profit. 
2.	Your group has detailed information about the datasets and the flowchart of the project. It seems to me that you really spend time on the project and already done some research. 
3.	I really like your idea of explicitly list the dataset in the appendix and state the function of different attributes. It will help the audience to understand your dataset as well as you problem when needed. 
Three things that can be improved:
1.	The proposal could be more organized and abstract. The objective of the project could be clearer especially for what is the algorithm you are trying to develop and the whole proposal should be less than 1 page. 
2.	Since you are considering different factors when making the customer pricing strategies, like competitor price, voice of customer and operation cost. It seems to me that some optimization algorithms need to use for finding the best parameters for each factor. Flexibility and cost model also mentioned in your proposal, so I assume some simulation methods may also be used. Considering the large amount of data you need to deal with, the algorithm you need to develop, and theses optimization or simulation methods you may need to apply, the whole project may be a little time consuming so a timeline including several milestones may need when you actually doing the project.
3.	Maybe combing how you are going to use these dataset and your steps statements will be helpful for the audience to understand your approach.

**Comment by amanjain454** [comment]
Thanks for your kind feedback. We have taken note of suggestions and have already implemented some of these in midterm report.
