### ISSUE TITLE
Final Peer Review - yz2454

### ISSUE THREAD

**Issue by iilove27** [amanjain454/4741-Project#9]
This project aims to predict uber price in the city of Bangalore in India. The team has its data from this company with roughly 900,000 raw data. The team uses various creative imputation methods to deal with missing values. It also incorporates learning algorithm that is used to predict cost while customer is placing an order. Overall, this project is highly applicable to real life and exciting in terms of its usage.

Things I like:

1. The various imputation methods used by the team are brilliant. For different features, the team chose different imputation methods to have missing value filled or dropped. All methods are explained well in the report.

2. The visualization helps me a lot understand the data distributions, how well the models work, as well as what is the order placing process. Two flow charts are necessary for the readers to understand what is the logic behind, and further to understand why the models should be chosen.

3. The fairness analysis part blocks gender feature to ensure that models do not generate any gender bias. The team also uses bar chart to visualize the blockage of that feature works. In terms of weapon of math destruction, the team also gives explanation why they do not think the models will not produce that result.

Things can be improved:

1. I noticed that "Out of city" trips records were removed, I do not understand why that should be done. If inter-city records are removed, the model will not learn to price inter-city trips, which can be something to improve if this project needs to expand its scale.

2.  One thing I didn't understand by reading the report is that why cost should be calculated. If it is not already in the dataset, then the model is basically trained to learn a function that is established in cost calculation, which is not applicable in real life; if it is in the dataset, then why should the team calculate cost again? Probably the team can make this point clearer to avoid confusion.

3. It is mentioned that polynomial transformation was used for "it", I am a little confused by what this "it" is referring to. If it refers to the planned_km feature, then the reason of this transformation was not explained; if this "it" refers to all features mentioned in the previous sentence, then I don't think one-hot encoding is really compatible with polynomial transformation. Maybe the team can clarify this point more.

**Comment by amanjain454** [comment]
Hi, Thanks for review and comments, 

Pricing methodology for a subscription business is very different from the on-demand ride-hailing. If you look at the methodology to arrive at pricing for subscription, its consists of all requests received at a point in time, run routing algorithm for all requests (so as to maximize vehicle utilization) and then figuring out how many vehicles are required and finally distributing this total cost to all requests. 

Now, most of the information required to run the above process will not be available (e.g. future requests may affect the routing efficiency and hence cost). So, while the customer is booking, you do not have enough info to calculate the price, but you still need to show a price estimate so that customers can make a decision and book ahead. This price estimate is what we are trying to learn.
further narrower the range of estimate, better it is. 

I hope this clarifies point 2. Point 1 (leaving out of the city) requests is a consequence of it. As each city will have its own nuances in terms of traffic, congestion and hence impact on routing. We wanted to focus on one specific city for this project.   

point 3 is miss from our side, I agree with you, it could have been more elaborate in the report.
